"""add is_anomaly column

Revision ID: 46e4445bd7eb
Revises: 8168b11f4aa6
Create Date: 2026-07-26 10:43:21.933071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46e4445bd7eb'
down_revision: Union[str, Sequence[str], None] = '8168b11f4aa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('is_anomaly', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'is_anomaly')
    # ### end Alembic commands ###
